### ISSUE TITLE
Melhorar ImageCache

### ISSUE THREAD

**Issue by andreanmasiro** [thefael/Pat#19]
O ImageCache atualmente tá expondo a lógica interna de cache dele, o que não é ideal. Eu não sou muito uma pessoa de orientação a objetos, mas um ótimo conceito que a gente pode aplicar aqui é o encapsulamento. Poderia ter uma interface do tipo `func get(url: URL) -> UIImage?` e `func put(url: URL, data: UIImage)`. Poderia até ser um cache genérico de qualquer key `: Hashable` pra qualquer valor. O que acha?

**Comment by thefael** [comment]
Não entendi a necessidade de uma interface. N poderia só implementar esses métodos lá no imageCache?

**Comment by thefael** [comment]
Sobre o cache genérico, legal. É uma coisa boa deixar as implementações mais genéricas?

**Comment by andreanmasiro** [comment]
Depende do esforço/benefício de ter uma implementação genérica. No seu caso, não é tão necessário, mas poderia ser usado nos 2 requests que tem no app. 

Quando eu falei `interface` não quis dizer protocolo. Interface quer dizer como é a cara da sua classe, como são as assinaturas das funções e tal. Mas protocolo também não seria má ideia, mas deixa pra depois kkkk

**Comment by thefael** [comment]
Tendeu hehe
